ARG GO_VERSION=1.17
ARG OS=bullseye
FROM golang:${GO_VERSION}-${OS}

ARG RUST_VERSION=1.56
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    RUST_VERSION=${RUST_VERSION}

RUN set -eux; \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --profile minimal --default-toolchain ${RUST_VERSION}; \
    chmod -R a+w ${RUSTUP_HOME} ${CARGO_HOME};