ARG UBUNTU_VERSION=14.04
FROM duskmoon/dev-env:ubuntu-${UBUNTU_VERSION}-base

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential subversion git-core libncurses5-dev \
    zlib1g-dev gawk flex quilt libssl-dev xsltproc \
    libxml-parser-perl mercurial bzr ecj cvs unzip \
    lib32z1 lib32z1-dev lib32stdc++6 libstdc++6 && \
    rm -rf /var/lib/apt/lists/*