ARG OS=bullseye
ARG RUST_VERSION=1.56.1
FROM rust:${RUST_VERSION}-slim-${OS}

ARG GO_VERSION=1.17.3
ENV PATH /usr/local/go/bin:$PATH
ENV GOLANG_VERSION ${GO_VERSION}
RUN apt update;\
    apt install -y wget;\
    wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz;\
    tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz;\
    rm go${GO_VERSION}.linux-amd64.tar.gz;\
    rm -rf /var/lib/apt/lists/*;