ARG UBUNTU_VERSION=20.04
FROM duskmoon/dev-env:ubuntu-${UBUNTU_VERSION}-base

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
    libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev \
    git-email libaio-dev libbluetooth-dev libbrlapi-dev libbz2-dev \
    libcap-dev libcap-ng-dev libcurl4-gnutls-dev libgtk-3-dev \
    libibverbs-dev libjpeg8-dev libncurses5-dev libnuma-dev \
    librbd-dev librdmacm-dev libsasl2-dev libsdl1.2-dev libseccomp-dev libsnappy-dev libssh2-1-dev \
    libvde-dev libvdeplug-dev libvte-2.91-dev libxen-dev liblzo2-dev \
    valgrind xfslibs-dev ninja-build && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root/programs
ENTRYPOINT ["zsh"]